from .mayBank.MayBank import MayBank
from .uob.Uob import Uob
from .ocbc.Ocbc import Ocbc
from .theReligionOfPeace.TheReligionOfPeace import TheReligionOfPeace
from .arthagraha.Arthagraha import Arthagraha
from .bankbba.Bankbba import Bankbba
from .jtrustbank.Jtrustbank import Jtrustbank
from .bankmayapada.Bankmayapada import Bankmayapada
from .boiindonesia.Boiindonesia import Boiindonesia
from .bankmuamalat.Bankmuamalat import Bankmuamalat
from .bankmestika.Bankmestika import Bankmestika
from .shinhan.Shinhan import Shinhan
from .banksinarmas.Banksinarmas import Banksinarmas
from .bankganesha.Bankganesha import Bankganesha
from .icbc.Icbc import Icbc
from .qnb.Qnb import Qnb
from .bankmega.Bankmega import Bankmega
from .bankbsi.Bankbsi import Bankbsi
from .kbbukopinsyariah.Kbbukopinsyariah import Kbbukopinsyariah
from .mncbank.Mncbank import Mncbank
from .megasyariah.Megasyariah import Megasyariah
from .bankindex.Bankindex import Bankindex